# Base image
FROM node:18-alpine

# Set working directory inside container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json for caching
COPY package*.json ./

# Install dependencies (including devDependencies)
RUN npm install

# Copy the rest of the app
COPY . .

# Expose port
EXPOSE 3000

# Start app with nodemon for hot reload
CMD ["npm", "run", "dev"]
