apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        # --- VIKTIG: Flux endrer tagen på linjen under automatisk basert på kommentaren! ---
        image: iseeanoob/to-do-list:1.0.39 # {"$imagepolicy": "flux-system:todo-policy"}
        ports:
        - containerPort: 3001
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: iseeanoob
        - name: DB_PASSWORD
          value: pass
        - name: DB_NAME
          value: mydb
        - name: JWT_SECRET
          value: your_jwt_secret
        - name: PORT
          value: "3001"
