name: Test and Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v6
      - name: sett opp node
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      - run: npm install
      - run: npm test